GameOverGames/GameOverGames/Controllers/InventoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BLL;
using BLL.Models;
using GameOverGames.Models;

namespace GameOverGames.Controllers
{
    public class InventoryController : Controller
    {
        private StoreLogic humanLg = new StoreLogic();
        // GET: Inventory
        public ActionResult inventoryIndex()
        {
            return View();
        }

        public ActionResult AddInventory()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddInventory(InventoryVM person)  //This is creating new products 
        {
            humanLg.AddInventory(InventoryVM.Map(person));
            return RedirectToAction("inventoryConfirmation");
        }

        public ActionResult inventoryConfirmation() //This confirms a product was created. Used for admin only, takes admin back 
        {                                           //to the Main admin page or back to the List or products            
            return View();
        }

        public ActionResult DisplayInventory()
        {
            return View(InventoryVM.Map(humanLg.DisplayInventory()));

        }

        public ActionResult DisplayInventoryEmployee()
        {
            return View(InventoryVM.Map(humanLg.DisplayInventory()));
        }

        public ActionResult DisplayInventoryCustomer()
        {
            return View(InventoryVM.Map(humanLg.DisplayInventory()));
        }

        public ActionResult UpdateInventory(int id)
        {
            InventoryVM human = InventoryVM.Map(humanLg.GetInventoryInfoByInventoryID(id));
            return View(human);
        }

        //POST UPDATEUSER
        [HttpPost]
        public ActionResult UpdateInventory(InventoryVM person)
        {
            humanLg.UpdateInventory(InventoryVM.Map(person));
            ModelState.Clear();
            ViewBag.Message2 = person.inventoryName + " Successfully Updated";
            return RedirectToAction("DisplayInventory");
        }
    }
}

GameOverGames/GameOverGames/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BLL;
using BLL.Models;

namespace GameOverGames.Controllers
{
    public class UserController : Controller
    {
        // GET: User
        public ActionResult Index()
        {
            return View();
        }

        private StoreLogic humanLg = new StoreLogic();

        // GET: Account
        public ActionResult AddUser()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddUser(UserVM person)
        {
            humanLg.AddUser(UserVM.Map(person));
            return RedirectToAction("Confirmation");
        }


        public ActionResult Confirmation()
        {
            return View();
        }

        public ActionResult DisplayAdmin()
        {

            return View();
        }

        public ActionResult DisplayEmployee()
        {

            return View();
        }

        public ActionResult DisplayCustomer()
        {

            return View();
        }

        //GET CUSTOMER LIST
        public ActionResult DisplayListofCustomers() //In the creation of new accouts, hide position and let admin update that to create employees
        {
            List<UserVM> UserList = UserVM.Map(humanLg.DisplayCustomer());
            return View(UserList);
        }

        public ActionResult DisplayListofCustomersforEmployee() //In the creation of new accouts, hide position and let admin update that to create employees
        {
            List<UserVM> UserList = UserVM.Map(humanLg.DisplayCustomer());
            return View(UserList);
        }

        //GET EMPLOYEE LIST
        public ActionResult DisplayListofEmployees()
        {
            List<UserVM> UserList = UserVM.Map(humanLg.DisplayEmployee());
            return View(UserList);
        }

        public ActionResult UpdateUserCustomer(int id)
        {
            UserVM human = UserVM.Map(humanLg.GetUserInfoByUserID(id));
            return View(human);
        }

        //POST UPDATEUSER
        [HttpPost]
        public ActionResult UpdateUserCustomer(UserVM person)
        {
            humanLg.UpdateUser(UserVM.Map(person));
            ModelState.Clear();
            ViewBag.Message2 = person.userName + " Successfully Updated";
            return RedirectToAction("DisplayListofCustomers");
        }

        public ActionResult UpdateUserEmployee(int id)
        {
            UserVM human = UserVM.Map(humanLg.GetUserInfoByUserID(id));
            return View(human);
        }

        [HttpPost]
        public ActionResult UpdateUserEmployee(UserVM person)
        {
            humanLg.UpdateUser(UserVM.Map(person));
            ModelState.Clear();
            ViewBag.Message2 = person.userName + " Successfully Updated";
            return RedirectToAction("DisplayListofEmployees");
        }

        public ActionResult UserDetails(int id)
        {
            UserVM human = UserVM.Map(humanLg.GetUserInfoByUserID(id));
            return View(human);
        }

        public ActionResult Login()
        {
            return View();
        }

        //POST Login
        [HttpPost]
        public ActionResult Login(UserVM person)
        {

            var usr = humanLg.Login(person.userName, person.userPassword);
            if (usr != null)
            {
                Session["UserID"] = usr.userID;
                Session["UserName"] = usr.userName;
                Session["Position"] = usr.userPosition;
                ViewBag.Message = person.userName;

                if (usr.userPosition == "Admin" || usr.userPosition == "admin")
                {
                    Session["Admin"] = new UserVM();
                    return RedirectToAction("DisplayAdmin");
                }
                else if (usr.userPosition == "Employee" || usr.userPosition == "employee")
                {
                    return RedirectToAction("DisplayEmployee");
                }
                else if (usr.userPosition == "Customer" || usr.userPosition == "customer")
                {
                    Session["Customer"] = new UserVM();
                    return RedirectToAction("DisplayCustomer");
                }
                else
                {
                    ModelState.AddModelError("", "Incorrect UserName or Password");
                }
            }
            else
            {
                return RedirectToAction("Login", "Index");
            }
            return View();
        }

        public ActionResult Logout()
        {
            Session.Clear();
            return View();
        }

    }
}

GameOverGames/GameOverGames/Views/Inventory/AddInventory.cshtml
@model GameOverGames.Models.InventoryVM

@{
    ViewBag.Title = "Create Inventory";
}

<h2>Please Enter in Product Information</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <ul class="nav navbar-nav navbar-right">
        <li><h4> @Session["UserName"]</h4></li>
    </ul>
    {
        var user = Session["UserName"] as UserControl;
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.Label("Product Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.inventoryName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.inventoryName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Price", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.inventoryPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.inventoryPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Stock", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.inventoryStock, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.inventoryStock, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
        }
}
<div>
    <h4>@Html.ActionLink("Back to Inventory List", "DisplayInventory", "Inventory", new { area = "areaName", id = Session["ID"] }, null)</h4>
</div>

GameOverGames/GameOverGames/Views/Inventory/DisplayInventory.cshtml
@model IEnumerable<GameOverGames.Models.InventoryVM>

@{
    ViewBag.Title = "DisplayInventory";
}

<h2>Inventory</h2>

<ul class="nav navbar-nav navbar-right">
    <li><h4> @Session["UserName"]</h4></li>
</ul>
@{
    var user = Session["UserName"] as UserControl;

<p>
    @Html.ActionLink("Create New", "AddInventory")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayName("Product Name")
        </th>
        <th>
            @Html.DisplayName("Price")
        </th>
        <th>
            @Html.DisplayName("Current Stock")
        </th>
        <th></th>
    </tr>

@foreach (var item in Model)
{
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.inventoryName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.inventoryPrice)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.inventoryStock)
        </td>
        <td>
            @Html.ActionLink("Edit", "UpdateInventory", new { id = item.inventoryID }) |
            @Html.ActionLink("Details", "Details", new { id = item.inventoryID }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.inventoryID })
        </td>
    </tr>

}
    <div>
        <h3>@Html.ActionLink("Back to Admin Page", "DisplayAdmin", "User", new { area = "areaName", id = Session["ID"] }, null)</h3>
    </div>
</table>
    }
@if (User.Identity != null)
{
    @Html.ActionLink("Logout", "Logout");
}

GameOverGames/GameOverGames/Views/Inventory/DisplayInventoryCustomer.cshtml
@model IEnumerable<GameOverGames.Models.InventoryVM>

@{
    ViewBag.Title = "DisplayInventoryCustomer";
}

<h1>Classic Games Selection</h1>
<ul class="nav navbar-nav navbar-right">
    <li><h4>@Session["UserName"]</h4></li>
</ul>
@{
    var user = Session["UserName"] as UserControl;
<table class="table">
    <tr>
        <th>
            @Html.DisplayName("Product Name")
        </th>
        <th>
            @Html.DisplayName("Price")
        </th>
        <th></th>
    </tr>

@foreach (var item in Model)
{
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.inventoryName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.inventoryPrice)
        </td>
        <td>
            @Html.ActionLink("Purchase", "Purchase", new { id = item.inventoryID }) |
            @Html.ActionLink("Details", "inventoryDetails", new { id = item.inventoryID }) |
        </td>
    </tr>
}

</table>
    }
@if (User.Identity != null)
{
    @Html.ActionLink("Logout", "Logout");
}

GameOverGames/GameOverGames/Views/Inventory/DisplayInventoryEmployee.cshtml
@model IEnumerable<GameOverGames.Models.InventoryVM>

@{
    ViewBag.Title = "DisplayInventoryEmployee";
}

<h2>Current Inventory</h2>
<ul class="nav navbar-nav navbar-right">
    <li><h4> @Session["UserName"]</h4></li>
</ul>
@{
    var user = Session["UserName"] as UserControl;
<table class="table">
    <tr>
        <th>
            @Html.DisplayName("Product Name")
        </th>
        <th>
            @Html.DisplayName("Price")
        </th>
        <th>
            @Html.DisplayName("Stock")
        </th>
        <th></th>
    </tr>

@foreach (var item in Model)
{
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.inventoryName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.inventoryPrice)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.inventoryStock)
        </td>
    </tr>
}

</table>
    }
@if (User.Identity != null)
{
    @Html.ActionLink("Logout", "Logout");
}

GameOverGames/GameOverGames/Views/Inventory/UpdateInventory.cshtml
@model GameOverGames.Models.InventoryVM

@{
    ViewBag.Title = "UpdateInventory";
}

<h2>UpdateInventory</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>InventoryVM</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.inventoryID)

        <div class="form-group">
            @Html.Label("Product Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.inventoryName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.inventoryName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Price", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.inventoryPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.inventoryPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Stock", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.inventoryStock, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.inventoryStock, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "DisplayInventory")
</div>

GameOverGames/GameOverGames/Views/Inventory/inventoryConfirmation.cshtml
@model GameOverGames.Controllers.UserVM
@{
    ViewBag.Title = "inventoryConfirmation";
}

<h2>Product Added</h2>

<h3>@Html.ActionLink("Back to List", "DisplayInventory")</h3>

<div>
    <h3>@Html.ActionLink("Back to Admin Page", "DisplayAdmin", "User", new { area = "areaName", id = Session["ID"] }, null)</h3>
</div>

GameOverGames/GameOverGames/Views/Inventory/inventoryIndex.cshtml
@{
    ViewBag.Title = "inventoryIndex";
}

<h2>inventoryIndex</h2>